ktor:
  application:
    modules:
      - fraudulent.link.tomochan.ApplicationKt.module
  deployment:
    port: 5000
postgres:
  embedded: true
  url: "jdbc:postgresql://localhost/default"
  user: "username"
  password: "password"