[versions]
kotlin-version = "2.1.20"
logback-version = "1.5.18"

[libraries]
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback-version" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-version" }